[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "lineage-client"
version = "0.0.1"

[tool.setuptools.packages.find]
where = ["."]
include = ["lineage_client*"]